feat: add images field

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -1,9 +1,13 @@
 name: Kustomize Image Tags
 description: Set Kustomization Image Tags and Commit changes
 inputs:
+  images:
+    description: Images to be pushed. Image tags will be used as suffix
+    required: false
   image-repos:
     description: Image Repositories
-    required: true
+    required: false
+    deprecationMessage: This input is deprecated. Use "images" instead
   image-tag:
     description: Custom Image Tag
     required: false
@@ -12,15 +16,23 @@ runs:
   using: composite
   steps:
     - name: Enforce Manifests .yaml Extension
-      run: |
-        find ./k8s/overlays/*/kustomization.yml && echo 'This is an intentional error. K8s manifests extension must be ".yaml".' && exit 1 || echo 'Everything good to go!'
       shell: bash
+      run: find ./k8s/overlays/*/kustomization.yml && echo 'This is an intentional error. K8s manifests extension must be ".yaml".' && exit 1 || echo 'Everything good to go!'
     - name: Set Kustomization Image Tags
+      shell: bash
       run: |
-        export IMAGE_REPOS="${{ inputs.image-repos }}"
         export IMAGE_TAG="$(make -Bsf ${{ github.action_path }}/Makefile IMAGE_TAG="${{ inputs.image-tag }}" image-tag)"
+        export IMAGES="${{ inputs.images }}"
+        export IMAGE_REPOS="${{ inputs.image-repos }}"
+        if [[ ! -z "${IMAGES}" ]] && [[ ! -z "${IMAGE_REPOS}" ]]
+        then
+          echo '"images" and "image-repos" inputs are not allowed simultaneously. "image-repos" is deprecated. Use "images" instead'
+        elif [[ -z "${IMAGES}" ]]
+        then
+          export IMAGES="${IMAGE_REPOS}"
+        fi
+
         make -Bf ${{ github.action_path }}/Makefile OVERLAY="integration" edit-kustomizations
         make -Bf ${{ github.action_path }}/Makefile OVERLAY="production" edit-kustomizations
         make -Bf ${{ github.action_path }}/Makefile OVERLAY="staging" edit-kustomizations
         make -Bf ${{ github.action_path }}/Makefile commit-kustomizations
-      shell: bash
